[tool.djlint]
profile="django"
ignore="H031"

[tool.pyright]
    typeCheckingMode = "strict" # "off", "basic", "standard", "strict"
    reportUnknownVariableType = false # silent for Django models
    reportUnknownMemberType = false # silent for Django models