# Generated by Django 5.2 on 2025-06-21 11:03

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_comment="The customer's first name", help_text="The customer's first name", max_length=50)),
                ('last_name', models.CharField(db_comment="The customer's last name", help_text="The customer's last name", max_length=50)),
                ('address_line1', models.CharField(db_comment='Address line 1 (e.g. street)', help_text='Address line 1 (e.g. street)', max_length=100)),
                ('address_line2', models.CharField(blank=True, db_comment='Address line 2 (e.g. apartment, suite, building)', help_text='Address line 2 (e.g. apartment, suite, building)', max_length=100, null=True)),
                ('address_city', models.CharField(db_comment='City, district, suburb, town or village', help_text='City, district, suburb, town or village', max_length=100)),
                ('address_postal_code', models.CharField(db_comment='ZIP or postal code', help_text='ZIP or postal code', max_length=10)),
                ('address_state', models.CharField(blank=True, db_comment='State, county, province or region', help_text='State, county, province or region', max_length=50, null=True)),
                ('address_country', django_countries.fields.CountryField(db_comment="Customer's country of residence", help_text="Customer's country of residence", max_length=2)),
                ('phone', models.CharField(db_comment="Customer's phone number", help_text="Customer's phone number", max_length=50)),
                ('passport', models.CharField(blank=True, db_comment="Customer's passport number if not Thai citizen", help_text="Customer's passport number if not Thai citizen", max_length=50, null=True)),
                ('created_at', models.DateTimeField(db_comment='The creation date of the customer', default=django.utils.timezone.now, help_text='The creation date of the customer')),
                ('user', models.ForeignKey(db_comment='The user linked to the customer', help_text='The user linked to the customer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
