# Generated by Django 5.2 on 2025-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_id',
            field=models.CharField(db_comment='The Stripe customer identifier linked to the customer', default='', help_text='The Stripe customer identifier linked to the customer'),
        ),
    ]
