# Generated by Django 5.2 on 2025-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripe_id',
            field=models.CharField(blank=True, db_comment='The Stripe customer identifier linked to the customer', help_text='The Stripe customer identifier linked to the customer'),
        ),
    ]
