# Generated by Django 5.2 on 2025-07-21 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='The last updated date of the model instance', help_text='The last updated date of the model instance'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(db_comment='The creation date of the model instance', default=django.utils.timezone.now, help_text='The creation date of the model instance'),
        ),
    ]
