# Generated by Django 5.2.1 on 2025-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(db_comment='The total passenger capacity', help_text='The total passenger capacity'),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(db_comment='Slugified combination of make and model', help_text='Slugified combination of make and model', unique=True),
        ),
    ]
