# Generated by Django 5.2.1 on 2025-05-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_capacity_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfeatureassignment',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AddField(
            model_name='carfeatureassignment',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carfeature'),
        ),
        migrations.AddField(
            model_name='carmedia',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
