# Generated by Django 5.2.1 on 2025-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carfeatureassignment_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='car.carfeature'),
        ),
        migrations.DeleteModel(
            name='CarFeatureAssignment',
        ),
    ]
