# Generated by Django 5.2.1 on 2025-05-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_features_delete_carfeatureassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeature',
            name='name',
            field=models.CharField(choices=[('AIRBAG', 'Airbag'), ('AIR_CONDITIONING', 'Air Conditioning'), ('ABS', 'Anti Lock Breaking System'), ('ASSISTED_STEERING', 'Assisted Steering'), ('BLUETOOTH', 'Bluetooth'), ('DASH_CAM', 'Dash Cam'), ('DRIVE_MODES', 'Drive Modes'), ('ESC', 'Electronic Stability Control'), ('GPS_NAVIGATION', 'Gps Navigation'), ('KEYLESS_ENTRY', 'Keyless Entry'), ('LED_HEADLIGHTS', 'Led Headlights'), ('POP_UP_HEADLIGHTS', 'Pop Up Headlights'), ('POWERED_WINDOWS', 'Powered Windows'), ('REAR_CAMERA', 'Rear Camera'), ('USB_PORTS', 'Usb Ports')], db_comment='The name of the car feature', help_text='The name of the car feature', max_length=25, unique=True),
        ),
    ]
