# Generated by Django 5.2.1 on 2025-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_carfeature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(choices=[('AWD', 'All Wheel Drive'), ('4WD', 'Four Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive')], db_comment='The car drivetrain', help_text='The car drivetrain'),
        ),
    ]
