# Generated by Django 5.2 on 2025-06-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_drivetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmedia',
            name='car',
            field=models.ForeignKey(db_comment='The car linked to the media', help_text='The car linked to the media', null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
