# Generated by Django 5.2 on 2025-07-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_carmedia_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_9_hours_cents',
            new_name='price_nine_hours_cents',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='price_12_hours_cents',
            new_name='price_twelve_hours_cents',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='price_24_hours_cents',
            new_name='price_twenty_four_hours_cents',
        ),
        migrations.AddField(
            model_name='car',
            name='price_six_hours_cents',
            field=models.IntegerField(db_comment='The price for a 9 hours rental, in cents', default=0, help_text='The price for a 9 hours rental, in cents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price_three_hours_cents',
            field=models.IntegerField(db_comment='The price for a 3 hours rental, in cents', default=2, help_text='The price for a 3 hours rental, in cents'),
            preserve_default=False,
        ),
    ]
