# Generated by Django 5.2 on 2025-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_rename_price_9_hours_cents_car_price_nine_hours_cents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_six_hours_cents',
            field=models.IntegerField(db_comment='The price for a 6 hours rental, in cents', help_text='The price for a 6 hours rental, in cents'),
        ),
    ]
