# Generated by Django 5.2 on 2025-07-21 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_price_six_hours_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='The last updated date of the model instance', help_text='The last updated date of the model instance'),
        ),
        migrations.AddField(
            model_name='carmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='The last updated date of the model instance', help_text='The last updated date of the model instance'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(db_comment='The creation date of the model instance', default=django.utils.timezone.now, help_text='The creation date of the model instance'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='The last updated date of the model instance', default=django.utils.timezone.now, help_text='The last updated date of the model instance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='created_at',
            field=models.DateTimeField(db_comment='The creation date of the model instance', default=django.utils.timezone.now, help_text='The creation date of the model instance'),
        ),
        migrations.AlterField(
            model_name='carmedia',
            name='created_at',
            field=models.DateTimeField(db_comment='The creation date of the model instance', default=django.utils.timezone.now, help_text='The creation date of the model instance'),
        ),
    ]
