# Generated by Django 5.2 on 2025-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_carfeature_updated_at_carmedia_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_twelve_hours_cents',
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, to='car.carfeature'),
        ),
    ]
