# Generated by Django 5.2 on 2025-06-21 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0007_alter_carmedia_car'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_comment='The start date of the booking', help_text='The start date of the booking')),
                ('end_date', models.DateTimeField(db_comment='The end date of the booking', help_text='The end date of the booking')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('CANCELED_BY_STAFF', 'Canceled By Staff'), ('CANCELED_BY_CUSTOMER', 'Canceled By Customer')], db_comment='The current booking status', help_text='The current booking status')),
                ('created_at', models.DateTimeField(db_comment='The creation date of the booking', default=django.utils.timezone.now, help_text='The creation date of the booking')),
                ('car', models.ForeignKey(db_comment='The car linked to the booking', help_text='The car linked to the booking', on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('customer', models.ForeignKey(db_comment='The customer linked to the booking', help_text='The customer linked to the booking', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
