# Generated by Django 5.2 on 2025-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('CANCELED_BY_STAFF', 'Canceled By Staff'), ('CANCELED_BY_CUSTOMER', 'Canceled By Customer')], db_comment='The current booking status', default='CONFIRMED', help_text='The current booking status'),
        ),
    ]
