# Generated by Django 5.2 on 2025-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_cents',
            field=models.IntegerField(db_comment='The total price of the booking, in cents', default=0, help_text='The total price of the booking, in cents'),
            preserve_default=False,
        ),
    ]
