# Generated by Django 5.2 on 2025-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_price_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('ACTIVE', 'Active'), ('UNPAID', 'Unpaid'), ('CANCELED_BY_STAFF', 'Canceled By Staff'), ('CANCELED_BY_CUSTOMER', 'Canceled By Customer')], db_comment='The current booking status', default='UNPAID', help_text='The current booking status'),
        ),
    ]
